name: Run Cypress and K6 Tests

on:
  push:
    branches:
      - main

jobs:
  frontend-tests:
    name: Run Cypress (Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        working-directory: web
        run: npm install

      - name: Rodar testes do Cypress (UI)
        working-directory: web
        run: npx cypress run

      - name: Upload de relatórios (opcional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-web-results
          path: web/cypress/screenshots

  backend-tests:
    name: Run Cypress (Backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar cache do Cypress
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Instalar dependências
        working-directory: backend
        run: npm install

      - name: Rodar testes do Cypress (API)
        working-directory: backend
        run: npx cypress run 


  stress-tests:
    name: Run K6 Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar K6
        run: |
          sudo apt update
          sudo apt install -y ca-certificates gnupg curl
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install -y k6

      - name: Rodar testes de stress com K6
        working-directory: k6
        run: k6 run index.js --vus 50 --duration 1m
